export const PolicyManagerAbi = [
  {
    inputs: [
      { name: "name", type: "string" },
      { name: "dailyLimit", type: "uint256" },
      { name: "weeklyLimit", type: "uint256" },
      { name: "monthlyLimit", type: "uint256" },
      { name: "perTxLimit", type: "uint256" },
    ],
    name: "createPolicy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "startHour", type: "uint256" },
      { name: "endHour", type: "uint256" },
      { name: "allowedDays", type: "bool[]" },
    ],
    name: "setTimeWindow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { name: "app", type: "address" },
      { name: "canTransfer", type: "bool" },
      { name: "canApprove", type: "bool" },
      { name: "maxAmount", type: "uint256" },
      { name: "allowedTokens", type: "address[]" },
    ],
    name: "setAppPermission",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "emergencyPause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "getPolicy",
    outputs: [
      { name: "name", type: "string" },
      { name: "isActive", type: "bool" },
      { name: "dailyLimit", type: "uint256" },
      { name: "weeklyLimit", type: "uint256" },
      { name: "monthlyLimit", type: "uint256" },
      { name: "perTxLimit", type: "uint256" },
      { name: "timeWindowEnabled", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ name: "account", type: "address" }],
    name: "getSpendingStats",
    outputs: [
      { name: "dailySpent", type: "uint256" },
      { name: "weeklySpent", type: "uint256" },
      { name: "monthlySpent", type: "uint256" },
      { name: "dailyRemaining", type: "uint256" },
      { name: "weeklyRemaining", type: "uint256" },
      { name: "monthlyRemaining", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
